openinfradev/decapod-site

- Jenkinsfile
* decapod-site-yaml을 사용하던걸 decapod-site로 변경
> fix Jenkinsfile to use decapod-site

- .github/workflows/merge_main.yml
> fix duplicated name of workflows

- hanu-reference-offline/lma/image-values.yaml
- hanu-reference-offline/lma/kustomization.yaml
- hanu-reference-offline/lma/site-values.yaml
- hanu-reference-offline/service-mesh/image-values.yaml
- hanu-reference-offline/service-mesh/kustomization.yaml
- hanu-reference-offline/service-mesh/site-values.yaml
* offline 환경을 위한 reference site 추가
> added new site for offline environment

- Jenkinsfile
site 를 선택해서 배포할 수 있도록 parameter 추가
> add SITE_NAME param

- .github/workflows/merge_main.yml
- .github/workflows/pr.yml
* decapod-manifests로 repository 명 변경
> renamed decapod-site-cd to decapod-manifests

- hanu-deploy-apps-offline/lma/image-values.yaml
- hanu-deploy-apps-offline/lma/kustomization.yaml
- hanu-deploy-apps-offline/lma/site-values.yaml
- hanu-deploy-apps-offline/service-mesh/image-values.yaml
- hanu-deploy-apps-offline/service-mesh/kustomization.yaml
- hanu-deploy-apps-offline/service-mesh/site-values.yaml
* hanu-deploy-apps-offline site 추가
> added offline site for hanu-deploy-apps

- hanu-deploy-apps-offline/lma/image-values.yaml
- hanu-deploy-apps-offline/lma/site-values.yaml
- hanu-deploy-apps-offline/service-mesh/image-values.yaml
site-value의 아래 내용 수정하였습니다.
- thanos-config 차트 누락
- 컨테이너 레지스트리 설정 누락
> Fix hanu deploy apps offline

- hanu-deploy-apps-offline/lma/image-values.yaml
- hanu-deploy-apps-offline/lma/site-values.yaml
- hanu-deploy-apps-offline/service-mesh/image-values.yaml
- hanu-deploy-apps-offline/service-mesh/site-values.yaml
오프라인 환경에서 실제 Helm 차트 저장소 URL로 대치될 문자열을 LOCAL_HELM_REPO 로, 로컬 레지스트 저장소 URL을 LOCAL_REGISTRY로 변경하였습니다.
> offline: change local helm repo and image registry url string

- README.md
- create_site.sh
* 새로운 사이트를 만들어주는 스크립트
* 사용법은 ./create_site.sh "사이트명"
> add new script to create site

- hanu-deploy-apps-offline/service-mesh/image-values.yaml
> added istio/jaeger images

- hanu-deploy-apps-offline/service-mesh/image-values.yaml
'/jaegertracing/' 이 누락되어 있어 수정하였습니다.
> fix jaeger images url

- hanu-reference/lma/site-values.yaml
* thanos-config error 수정
* endpoint ip may not be in the loopback range (127.0.0.0/8)
* 127.0.0.0/8 대역이 아닌 실제 아이피를 넣어야함 일단 가상의 아이피를 넣음
> fix: thanos config error

- gate-centos-lb-ceph-online-multinodes/lma/site-values.yaml
- hanu-reference/lma/site-values.yaml
> test for alertmanager

- gate-centos-lb-ceph-online-multinodes/lma/site-values.yaml
- hanu-reference-offline/lma/site-values.yaml
- hanu-reference/lma/site-values.yaml
* related https://github.com/openinfradev/decapod-base-yaml/pull/84
> merge addons and fed-addons

- hanu-reference-offline/lma/image-values.yaml
> fix rendering error

- hanu-deploy-apps-offline/lma/site-values.yaml
- hanu-deploy-apps/openstack/site-values.yaml
스토리지 클래스 기본 이름을 'taco-storage'로 변경하였습니다.
관련 논의: https://github.com/openinfradev/taco-gate-inventories/pull/20
> use 'taco-storage' for storageclass name

- Jenkinsfile
- 어드민 노드 아이피를 사용자에게 입력받는 것으로 단순화
- 오프라인 파라미터 추가
-  참고: openinfradev/taco-gate-inventories@4687b58#diff-27c7f3610e87a432f4a429dc9ec3809f72b84a8ede91f51e140ff3f6a7214f4f
> V1: jenkins: add offline support

- hanu-deploy-apps/service-mesh/image-values.yaml
- hanu-deploy-apps/service-mesh/kustomization.yaml
- sync jaeger image between hanu-deploy-apps and offline
- fix profer query image in hanu-deploy-apps-offline
> Fix jaeger image

- hanu-deploy-apps/service-mesh/kustomization.yaml
image-values.yaml의 위치가 잘못되어 수정
> fix yaml value

- gate-centos-lb-ceph-online-multinodes/lma/site-values.yaml
- hanu-deploy-apps/lma/site-values.yaml
taco's default storage class was changed from rbd to taco-storage
> fix storageclass to taco-storage

- Jenkinsfile
online 환경으로 deploy-apps-v1 job 테스트 시 에러가 발생하여, 이를 수정하였습니다.
https://jenkins.hanu-ci.io/job/deploy-apps-v1/32/console
```
hudson.remoting.ProxyException: groovy.lang.MissingPropertyException: No such property: offlineArg for class: WorkflowScript
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)
```
> fix offline argument

- .github/workflows/pr.yml
- .github/workflows/render-cd.sh
- .github/workflows/render.sh
- .gitignore
- hanu-reference/tks-cluster/kustomization.yaml
- hanu-reference/tks-cluster/site-values.yaml
* tks-cluster app group 을 추가
* offline 환경은 고려하지 않으므로 online 사이트에만 추가
* vpc 및 subnet 값은 실제 테스트할 수 있는 vpc값으로 추가. (decapod-manifests 생성 및 argocd 연동까지 테스트하기 위해)
> Add tks-cluster app group into hanu-reference site

- .github/workflows/render.sh
release-1.0에 main 브랜치 업데이트 내용 반영 및 render 스크립트에서 사용하는 decapod-base 브랜치를 release-1.0으로 변경하였습니다.
> update render script from main branch

- README.md
- gate-centos-lb-ceph-online-multinodes/lma/site-values.yaml
- gate-centos-lb-ceph-online-multinodes/openstack/site-values.yaml
- hanu-reference-offline/decapod-controller/image-values.yaml
- hanu-reference-offline/decapod-controller/kustomization.yaml
- hanu-reference-offline/decapod-controller/site-values.yaml
- hanu-reference/decapod-controller/kustomization.yaml
- hanu-reference/decapod-controller/site-values.yaml
- hanu-reference/lma/site-values.yaml
- hanu-reference/openstack/site-values.yaml
decapod-controller의 manifest 생성을 위해 base와 매핑되도록 site 설정 추가함.
> add decapod-controller conf to hanu-reference site

- Jenkinsfile
* Jenkins deploy-apps-v2 로 만들어서 테스트하였습니다. https://jenkins.hanu-ci.io/job/deploy-apps-v2
* workflow triggering은 정상 작동하였으나 lma 서비스가 제대로 안뜨는 문제가 있습니다. (이는 다른 PR로 수정할 예정)
* 연관 PR
* https://github.com/openinfradev/taco-gate-inventories/pull/25
> fix: applied changes on decapod v2

- hanu-reference-offline/decapod-controller/site-values.yaml
- hanu-reference/decapod-controller/site-values.yaml
https://github.com/openinfradev/decapod-base-yaml/pull/103 에 맞도록 함께 수정함
> modify app names in unified manner

- hanu-reference/lma/site-values.yaml
fed-master의 역할 중 필요한 부분에 대한 prometheus로 이동
- fed-master 제거
> TACODEV-798: remove fed-master

- hanu-reference/sealed-secrets/kustomization.yaml
- hanu-reference/sealed-secrets/site-values.yaml
[decapod-issues/16] sealed-secrets-controller 및 Kubed 설치 자동화를 위해 차트 추가합니다
https://github.com/openinfradev/decapod-base-yaml/pull/123 과 함께 merge되어야 합니다.
> add sealed-secrets app group

- .github/workflows/render-cd.sh
https://github.com/openinfradev/tks-issues/issues/137
> update render-cd script to use new helm2yaml image

- hanu-reference/service-mesh/site-values.yaml
service-mesh version upgrade 를 위한 수정
> upgrade istio: v1.11.7, jaeger: 1.24.0,  kiali: v1.38.1

- hanu-reference-offline/admin-tools/image-values.yaml
- hanu-reference-offline/admin-tools/kustomization.yaml
- hanu-reference-offline/admin-tools/site-values.yaml
- hanu-reference/admin-tools/kustomization.yaml
- hanu-reference/admin-tools/site-values.yaml
keycloak operator와 operator 를 통한 keycloak 배포용 자원 추가 입니다.
> add keycloak-operator and resources

- hanu-reference-offline/service-mesh/site-values.yaml
- hanu-reference/service-mesh/site-values.yaml
tks-portal 설치를 위한 site-value 를 추가합니다.
테스트를 위해 임시 정보를 사용하였습니다.
> feature. add_tks_portal

- hanu-reference-offline/service-mesh/site-values.yaml
- hanu-reference/service-mesh/site-values.yaml
servicemesh portal decapod 체계에서 제외합니다.
포함시 다시 논의합니다.
> feature. remove servicemesh-portal from decapod

- hanu-reference/service-mesh/site-values.yaml
es user 를 taco-jaeger 에서 taco-fluentbit 으로 변경
> change es jaeger user to fluentbit

- decapod-reference-offline/lma/site-values.yaml
- decapod-reference/lma/site-values.yaml
> [bugfix] fix taco_cluster value

- decapod-reference/openstack/site-values.yaml
> remove duplicate key

- .github/workflows/render-cd.sh
- decapod-reference/tks-cluster-aws/site-values.yaml
- decapod-reference/tks-cluster-common/kustomization.yaml
- decapod-reference/tks-cluster-common/site-values.yaml
https://github.com/openinfradev/decapod-base-yaml/pull/164 사전에 반영이 되어야 합니다.
BYOH 프로바이더 등 다른 cluster api 인프라 프로바이더 추가를 위해 공통 부분(tks-cluster-common)과 프로바이더 전용 부분 (tks-cluster-aws) 으로 분리하였습니다.
> support multiple infra provider

- .github/workflows/render-cd.sh
클러스터 ID 형식 변경으로 UUID를 사용하지 않게되어 관련 부분을 제거합니다.
> UUID 첫 그룹 8자리를 클러스터 이름으로 사용하도록 수정했던 부분을 원복

- .github/workflows/render-cd.sh
- aws-reference/lma/site-values.yaml
- byoh-reference/lma/site-values.yaml
- decapod-reference-offline/lma/site-values.yaml
로깅관련 신규기능 지원
- multi elasticsearch를 지원하면서 바뀐 value 구조 적용
- helm-v1.9.x를 갖고 있는 이미지 적용
- 위 이미지의 사용방법차이에 따른 워크플로우 수정
> 로깅관련 신규기능 지원

- byoh-reference/lma/site-values.yaml
- decapod-reference-offline/lma/image-values.yaml
- decapod-reference-offline/lma/site-values.yaml
fluentbit-operator에서 fluent-operator로 변경한 내역을 모든 reference에 반영
안되면
- 구축을 나가기 위한 offline 생성시 문제발생
- byoh 기반 사이트 만들때 에러발생
**결국은 동일값 복제의 이슈**
> qpply the chart change to all references(byoh,offline)

- aws-msa-reference/lma/site-values.yaml
- aws-reference/lma/site-values.yaml
from thanos-minio to minio
due to change of minio-installation from embeded to single
> thanos-config: change minio name #145

- aws-msa-reference/lma/site-values.yaml
- aws-reference/lma/site-values.yaml
- byoh-reference/lma/site-values.yaml
- decapod-reference-offline/lma/site-values.yaml
sha 포함되어 이미지 관련 에러나는 부분 해소를 위해 강제로 sha 제거
> prometheus: force remove sha from image

- aws-msa-reference/lma/site-values.yaml
- aws-reference/lma/site-values.yaml
change loki connection on grafana
> fluentbit: change the default loki target

- aws-msa-reference/service-mesh/site-values.yaml
add nodeAffinity for Jaeger component
> add jaeger nodeAffinity

- aws-msa-reference/service-mesh/site-values.yaml
- add jaeger image url
- add istio-ingress-gateway image url
> add jaeger image and istio-ingress-gateway image url

- aws-msa-reference/service-mesh/site-values.yaml
- add pilot image url
- add kiali nodeSelector
> add pilot image url

- aws-msa-reference/lma/site-values.yaml
> event-exporter: add a way to configure cluster-name

- aws-reference/lma/site-values.yaml
LOKI 연동을 위한 파라미터 도입
현재 한꺼번에 수정하기 대상
- fluentbit
- kubernetes-event-exporter
> add variables for loki connection

- aws-msa-reference/lma/site-values.yaml
- aws-reference/lma/site-values.yaml
앞에 변수로 loki 설정하는 부분에 msa-reference에도 적용..
각 템플릿에도 적용해야 하는데 이건 실제 사용전 신경쓰는 것으로 하겠습니다.
> align with aws-reference and aws-msa-reference each other

- aws-msa-reference/tks-cluster/site-values.yaml
- aws-reference/tks-cluster/site-values.yaml
- eks-reference/lma/kustomization.yaml
- eks-reference/lma/site-values.yaml
- eks-reference/tks-cluster/kustomization.yaml
- eks-reference/tks-cluster/site-values.yaml
AWS EKS 클러스터 생성을 위한 레퍼런스 사이트를 추가합니다.
> eks-eference 사이트 추가

- aws-msa-reference/lma/site-values.yaml
배경:
- aws-msa-reference 사이트 기존 설정은 bitnami minio 기준의 설정
수정내용:
- minio-official 의 차트 기준에 맞추어 수정함
> aws-msa-reference 사이트에 minio-official에 맞춘 value 반영

- aws-msa-reference/service-mesh/site-values.yaml
- change image url
- harbor 에는 변경된 이미지를 업로드 하였음
> change original images url to harbor image url

- aws-msa-reference/lma/site-values.yaml
> Thanos: set as a global variable for store endpoints

- aws-msa-reference/tks-cluster/site-values.yaml
클러스터 생성시 tks node 의 개수를 지정할 수 있도록 site value 추가
연관 변경
. tks-flow
. tks-api
> feature. add stack params

- aws-reference/lma/site-values.yaml
- eks-reference/lma/site-values.yaml
기존에 적용된 내역 
aws-reference, eks-reference 에도 반영
> synchronize sites

- aws-msa-reference/lma/site-values.yaml
- eks-msa-reference/lma/site-values.yaml
> thanos: add ruler rules for tks

- aws-msa-reference/tks-cluster/site-values.yaml
아래 3개를 모두 같이 merge 해야 함
- decapod-base-yaml
- decapod-site
- tks-flow
> add argo-rollouts chart

- aws-msa-reference/lma/site-values.yaml
- aws-reference/lma/site-values.yaml
- eks-msa-reference/lma/site-values.yaml
- eks-reference/lma/site-values.yaml
byoh를 제외한 4개의 site에 대한 Grafana의 서비스 타입 변경(ClusterIP -> LoadBalancer)
적용 site:
- aws-reference
- aws-msa-reference
- eks-reference
- eks-msa-reference
> minor fix: set grafana servicetype to loadbalancer

- aws-msa-reference/lma/site-values.yaml
- aws-reference/lma/site-values.yaml
- eks-msa-reference/lma/site-values.yaml
- eks-reference/lma/site-values.yaml
> alertmanager: update configuration for tks

- aws-msa-reference/lma/site-values.yaml
- aws-reference/lma/site-values.yaml
- eks-msa-reference/lma/site-values.yaml
- eks-reference/lma/site-values.yaml
grafana 설정 파일(grafana.ini) 파일에 대한 정상적인 파싱을 위해 grafana.ini -> grafana\.ini로 수정
> minor fix: change to backslash dot(\.) from grafana.ini

- aws-msa-reference/lma/site-values.yaml
- aws-reference/lma/site-values.yaml
- eks-msa-reference/lma/site-values.yaml
- eks-reference/lma/site-values.yaml
thanos 질의 성능 향상을 위한 query frontend 활성화 입니다.
> thanos: enable thanos-query-frontend

- eks-msa-reference/tks-cluster/site-values.yaml
- eks-reference/tks-cluster/site-values.yaml
cluster-autoscaler 버전을 최신 버전으로 업데이트합니다.
> tks-cluster: cluster-autoscaler: update version to v1.25.2

- aws-msa-reference/lma/site-values.yaml
- aws-reference/lma/site-values.yaml
- eks-msa-reference/lma/site-values.yaml
- eks-reference/lma/site-values.yaml
classic lb를 network lb 타입으로 변경합니다.
- 성능도 좋아질것이고
- app serving에서 alb를 사용하는 제한의 한계랑 겹치는 부분도 사라짐
> all: change loadbalancer type from classic-lb to nlb

- aws-msa-reference/lma/site-values.yaml
- aws-reference/lma/site-values.yaml
- eks-msa-reference/lma/site-values.yaml
- eks-reference/lma/site-values.yaml
namespace를 현재의 lma로 고정하는 것이 아니라 지정해서 설치할 수 있도록 합니다.
실제 base에도 설정변경이 필요하므로 추후 test&merge 하는 것으로 ...
> lma: define install base namespace for lma

- aws-msa-reference/lma/site-values.yaml
- aws-reference/lma/site-values.yaml
- eks-msa-reference/lma/site-values.yaml
- eks-reference/lma/site-values.yaml
alert 발생을 위해 조정했던 값들을 원래 의도했던 수치나 매트릭으로 변경
> thanos: update alert to real factor

- aws-msa-reference/lma/site-values.yaml
- aws-reference/lma/site-values.yaml
- eks-msa-reference/lma/site-values.yaml
- eks-reference/lma/site-values.yaml
loki와 minio의 자원들이 랜덤하게 뿌려지고 있어 확인해보니 nodeselector 지정이 안되어 있었습니다.
이에 대한 taco-lma=enabled 로 지정된 노드로 보내는 수정
> loki,minio: define nodeselector on loki and minio

- eks-msa-reference/tks-cluster/site-values.yaml
- eks-reference/tks-cluster/site-values.yaml
사용자 클러스터 bastion 호스트가 생성되는 오류(잘못된 오버라이딩 문법 사용)를 수정합니다.
> eks*-reference: disable bastion host

- aws-reference/tks-admin-tools/kustomization.yaml
- aws-reference/tks-admin-tools/site-values.yaml
- byoh-reference/tks-admin-tools/kustomization.yaml
- byoh-reference/tks-admin-tools/site-values.yaml
- eks-reference/tks-admin-tools/kustomization.yaml
- eks-reference/tks-admin-tools/site-values.yaml
https://github.com/openinfradev/decapod-base-yaml/pull/264 과 함께 리뷰되어야 합니다.
https://github.com/openinfradev/tks-issues/issues/861
> add tks-admin-tools

- byoh-reference/tks-cluster/site-values.yaml
K8S 버전을 TKS Harbor에서 지원되는 버전으로 업데이트 합니다.
> byoh-reference: tks-cluster: update k8s version to v1.25.11

- byoh-reference/tks-cluster/site-values.yaml
TKS API에서 가져오는 cluster info를 통해 클러스터 엔드포인트가 사이트 변수에 설정될 수 있도록 추가: 실제 치환은 tks-flow에서 이루어짐 (https://github.com/openinfradev/tks-flow/pull/258)
> Byoh 클러스터 엔드포인트 설정 추가

- byoh-reference/tks-cluster/site-values.yaml
BYOH 클러스터의 노드 숫자를 설정 가능하도록 수정합니다.
> byoh: make the number of nodes configurable

- byoh-reference/lma/site-values.yaml
Node port를 사용하도록 하는 byoh용 lma 값들 최초추가
> Node port를 사용하도록 하는 byoh용 lma 값들 최초추가

- aws-msa-reference/lma/site-values.yaml
- aws-reference/lma/site-values.yaml
- byoh-reference/lma/site-values.yaml
- eks-msa-reference/lma/site-values.yaml
- eks-reference/lma/site-values.yaml
thanos -> tks-thanos
minio -> tks-minio
> Minio의 버킷 생성 명 변경

- eks-msa-reference/service-mesh/site-values.yaml
eks-msa-reference 가 누락되어 추가합니다.
> fix eks-msa-reference

- byoh-reference/tks-admin-tools/site-values.yaml
- byoh-ssu-reference/tks-admin-tools/site-values.yaml
- byoh-stage-reference/tks-admin-tools/site-values.yaml
- byoh-suy-reference/service-mesh/site-values.yaml
2023.11.01 SKB 환경에서 admin cluster 2차 구축 과정에서 나온 필요 수정 사항을 반영하였습니다.
> minor modification for skb installation

- aws-reference/tks-admin-tools/site-values.yaml
- byoh-suy-reference/service-mesh/site-values.yaml
- byoh-suy-reference/tks-admin-tools/site-values.yaml
이전 PR 에서 SKB 설치를 위한 수정 사항 반영 중 실수로 byoh-suy-reference의 service-mesh 파일의 수정이 있어 원복.
의도대로 byoh-suy-reference의 tks-admin-tools를 수정
> bugfix. fix unintended modification on msa

- eks-msa-reference/service-mesh/site-values.yaml
Kiali와 Jaeger의 SSO 지원을 위한 PR. 
우선, eks-msa-reference에서 tks-flow와 함께 개발 및 테스트 후 다른 site에도 추가하여 PR 올리겠습니다.
> Kiali 및 Jaeger SSO 기능 추가

- byoh-reference/lma/site-values.yaml
thanos query-frontend의 nodeport설정입니다.
> thanos: define nodeport for thanos-query-frontend

- byoh-reference/lma/site-values.yaml
- eks-msa-reference/service-mesh/site-values.yaml
> 20231103 release to develop

- byoh-reference/lma/site-values.yaml
https://github.com/openinfradev/decapod-base-yaml/pull/287 와 동일
> bugfix: change keys for thanos service

- aws-msa-reference/service-mesh/site-values.yaml
- eks-msa-reference/service-mesh/site-values.yaml
> change k8ssandra replicas to 3

- aws-msa-reference/policy/kustomization.yaml
- aws-msa-reference/policy/site-values.yaml
- aws-reference/policy/kustomization.yaml
- aws-reference/policy/site-values.yaml
- eks-msa-reference/policy/kustomization.yaml
- eks-msa-reference/policy/site-values.yaml
- eks-reference/policy/kustomization.yaml
- eks-reference/policy/site-values.yaml
- https://github.com/openinfradev/tks-flow/pull/256
- https://github.com/openinfradev/decapod-flow/pull/130
- https://github.com/openinfradev/decapod-base-yaml/pull/265
- https://github.com/openinfradev/decapod-site/pull/178
- https://github.com/openinfradev/helm-charts/pull/216
> policy: add a decapod app for policies

- aws-msa-reference/lma/site-values.yaml
- aws-reference/lma/site-values.yaml
- byoh-reference/lma/site-values.yaml
- eks-msa-reference/lma/site-values.yaml
- eks-reference/lma/site-values.yaml
> Policy ruler

- aws-msa-reference/lma/site-values.yaml
- aws-reference/lma/site-values.yaml
- byoh-reference/lma/site-values.yaml
- eks-msa-reference/lma/site-values.yaml
- eks-reference/lma/site-values.yaml
thanos-ruler 를 tks system 에서 컨트롤하기 위해 LoadBalancer 를 추가합니다.
byoh를 위한 tks-endpoint-secret 작업은 추후 byoh 작업시 진행합니다.
> feature. change service type LoadBalancer for thanos-ruler

- aws-msa-reference/lma/site-values.yaml
- aws-reference/lma/site-values.yaml
- byoh-reference/lma/site-values.yaml
- byoh-ssu-reference/lma/site-values.yaml
- byoh-stage-reference/lma/site-values.yaml
- eks-msa-reference/lma/site-values.yaml
- eks-reference/lma/site-values.yaml
정책기능 추가하면서 함께 추가된 네임스페이스(gatekeeper-system)에 대한 로깅 추가
> fluentbit: add collecting targets for policy-serving

- aws-msa-reference/lma/site-values.yaml
- aws-reference/lma/site-values.yaml
- byoh-reference/lma/site-values.yaml
- eks-msa-reference/lma/site-values.yaml
- eks-reference/lma/site-values.yaml
아래내역은 세트임
- https://github.com/openinfradev/helm-charts/pull/240
- https://github.com/openinfradev/tks-flow/pull/377
- https://github.com/openinfradev/decapod-site/pull/242
- https://github.com/openinfradev/decapod-base-yaml/pull/323
> User logging 지원

- byoh-reference/lma/site-values.yaml
byoh-reference 에 명시적으로 LoadBalancer 로 설정되어 있는 곳 삭제
> trivial. remove service type LoadBalaner from thanos-ruler

- byok-reference/lma/kustomization.yaml
- byok-reference/lma/site-values.yaml
- byok-reference/policy/kustomization.yaml
- byok-reference/policy/site-values.yaml
- byok-reference/sealed-secrets/kustomization.yaml
- byok-reference/sealed-secrets/site-values.yaml
- byok-reference/service-mesh/kustomization.yaml
- byok-reference/service-mesh/site-values.yaml
- byok-reference/tks-admin-tools/kustomization.yaml
- byok-reference/tks-admin-tools/site-values.yaml
- byok-reference/tks-cluster/kustomization.yaml
- byok-reference/tks-cluster/site-values.yaml
> feature. add byok-reference

- aws-msa-reference/lma/site-values.yaml
- aws-reference/lma/site-values.yaml
- eks-msa-reference/lma/site-values.yaml
- eks-reference/lma/site-values.yaml
@intelliguy 님
lma 삭제시 tks-loki-user 가 없어 에러가 발생하고 있습니다. 이 변경이 옳은 변경이 맞는지 판단하시어 merge 부탁 드립니다.
> bugfix. add s3 bucket 'tks-loki-user'
