openinfradev/decapod-site

.github/workflows/merge_main.yml
.github/workflows/pr.yml
.github/workflows/render-cd.sh

추가된 액션은 다음의 두가지 작업을 수행합니다.
1. pr의 source  branch 내용을 토대로 decapod rendering을 수행하여 decapod manifest를 만들고 
2. decapod manifest를 chart별로 [kind]_[name].yaml 파일로 분해한 후
3. 이를 https://github.com/openinfradev/decapod-site-cd 로 temporary_from_pr branch로 push
4. 이때 이를 발생시킨 commit의 hash코드가 commit message라 남습니다.
1. pr의 source  branch 내용을 토대로 decapod rendering을 수행하여 decapod manifest를 만들고 
2. decapod manifest를 chart별로 [kind]_[name].yaml 파일로 분해한 후
3. 이를 https://github.com/openinfradev/decapod-site-cd 의 main branch로 push 
4. 이때 이를 발생시킨 commit의 hash코드가 commit message라 남습니다.

TACODEV-776: generate resource yamls from helmrelease mannifest

---

gate-centos-lb-ceph-online-multinodes/lma/site-values.yaml
hanu-deploy-apps/lma/site-values.yaml

for hanu-deploy-apps and gate-centos-lb-ceph-online-multinodes
- alertmanager nodePort enabled
- alertmanagerConfigSelector setting
- slack_api_url fix

Fix prometheus alert url

---

hanu-deploy-apps-offline/lma/image-values.yaml

In the taco archive, the image file is stored using only the name of
the container image, so this PS remove owner info at image value.
현재 taco 아카이브에는 컨테이너 이미지 저장 시 소유자 정보가 없는 순수 이름만 태그하여 저장하기 때문에
image 이름에 소유자 정보가 있는 값을 수정하였습니다.

Delete owner info for local registry

---

hanu-deploy-apps-offline/lma/image-values.yaml

kube-state-metrics chart use 'registry' value for image
kube-state-metrics chart에서 Image value를 registry, repository, tag로 설정하고 있어서 누락된 registry value를 추가해주었습니다.

Add registry to kube-state-metrics

---

hanu-deploy-apps-offline/service-mesh/image-values.yaml

service-mesh-resource 차트의 이미지 관련 변수 참조가 잘못된 부분을 수정하였습니다.
참고: https://github.com/openinfradev/helm-charts/blob/e0010a44fc1069e3837a649dcfa48c1e903d699a/service-mesh-resource/values.yaml#L22

hanu-deploy-apps-offline: fix service-mesh-* image overrrides

---

gate-centos-lb-ceph-online-multinodes/service-mesh/kustomization.yaml
gate-centos-lb-ceph-online-multinodes/service-mesh/site-values.yaml
hanu-reference-offline/service-mesh/image-values.yaml
hanu-reference/service-mesh/kustomization.yaml
hanu-reference/service-mesh/site-values.yaml

helm-chart 가 먼저 적용되어야 함.
관련 PR: [openinfradev/helm-charts/pull/48]
decapod-base-yaml 이 함께 적용되어야 함
관련 PR: [openinfradev/decapod-base-yaml/pull/88]
site-values.yaml 을 추가하여 values 값을 오버라이드 할 수 있게 수정
아래 label 을 노드에 추가해야 함 (추후 tacoplay 에 추가 예정)
1. servicemesh control node
servicemesh=enabled
2. servicemesh ingress node
taco-ingress-gateway=enabled
3. servicemesh egress node
taco-egress-gateway=enabled

servicemesh refactoring

---

.github/workflows/render-cd.sh
.github/workflows/render.sh
.github/workflows/stale.yml

내용
현재 사용하는 manifest는 helm repo에 저장된 chart를 기반으로 돌아가도록 되어있다.
개발의 편의성을 위해 github이나 local에 올라간 소스를 기반으로 배포하는 것을 위한 유틸리티가 있다면 좋겠다.
수행내역
spec.chart를 재정의해서 필요한 기능을 수행할수 있도록 제반 유틸리티 수정
type: helmrepo
repository: https://prometheus-community.github.io/helm-charts
name: kube-prometheus-stack
version: 14.5.0
또는
type: git
repository: git@github.com:helm/charts
name: charts/stable/prometheus-operator
version: master 
와 같이 정의 가능하고 type은 생략할 수 있고 기본값 helmrepo로 산정되어 작업됨
type이 git이면 repository는 git 과 같은 의미 name은 path와 같은 의미 version은 ref와 같은 의미로 동작하도록 한다.
산출물
https://github.com/openinfradev/decapod-site/pull/33
https://github.com/openinfradev/decapod-base-yaml/pull/87
https://github.com/openinfradev/kustomize-helm-transformer/pull/30

Dev support GitHub directory

---

hanu-reference-offline/lma/image-values.yaml
hanu-reference-offline/lma/site-values.yaml

https://github.com/openinfradev/decapod-site/pull/57 에서 발생하는 validation 오류 (hanu-reference-offline 사이트의 fed-master 삭제 부분 누락) 등을 수정하기 위해서 hanu-reference 내용과 동기화하였습니다.

hanu-reference-offline/lma sync with hanu-reference

---

hanu-reference/lma/site-values.yaml

의존성: 아래 PR이 먼저 머지가 되어야합니다.
- https://github.com/openinfradev/helm-charts/pull/67  (완료)
- https://github.com/openinfradev/decapod-base-yaml/pull/110 (완료)
아마존 환경에서 테스트한 마스터노드 label, toleration을 추가하였습니다.

Add prepare-etcd-secret chart for lma

---

hanu-reference/lma/site-values.yaml
hanu-reference/service-mesh/site-values.yaml

LMA 의 grafana 가 모든 namespace 의 cm 을 discovery 할 수 있게 변경 (istio-namespace 의 grafana dashboard 를 찾을 수 있게 수정)
LMA addons 에 있는 istio 관련 리소스(grafana dashboard, ServiceMonitor, PodMonitor, Prometheusrule) 을 disable 시킴
istio 의 grafana dashboard 의 label 을 grafana 가 discovery 할 수 있게 "grafana_dashboard" 로 변경
ELB 와 istio gateway 를 연결할 수 있게 istio gateway 의 health check nodeport 를 지정할 수 있게 변경
Jaeger 의 web base path 를 "/" 로 추가

Change to grafana discovery all namesapce

---

.github/workflows/render-cd.sh
create_site.sh
hanu-reference-offline/decapod-controller/image-values.yaml
hanu-reference-offline/lma/image-values.yaml

오프라인 혹은 내부 저장소/레지스트리 운영 환경 등 상황에 대응하기 위해 관련 부분을 설정할 수 있도록 수정하였습니다.

render-cd  스크립트를 오프라인 등 환경에 사용하기 위해 설정 가능한 부분을 추가

---

hanu-reference-offline/lma/image-values.yaml

https://github.com/openinfradev/tacoplay/commit/32d7eb56d3d5c8777059474f150822d30a1be84b 반영으로 site-prepare 과정에서 오프라인 환경을 위한 이미지 태깅 형식이 변경되어 이를 반영합니다.
컨테이너 레지스트리 주소 없이 묵시적으로 docker.io를 사용하는 이미지 주소의 경우,
- 기존: organization 부분이 제거되어 내부 레지스트리에 저장 (예: ORG/IMAGE_A -> private_registry:5000/IMAGE_A)
- 변경: 원본 주소 값에 내부 레지스트리 내용만 추가 (예: ORG/IMAGE_A -> private_registry:5000/ORG/IMAGE_A)

hanu-reference-offline: fix image urls

---

hanu-reference-offline/service-mesh/image-values.yaml
hanu-reference-offline/service-mesh/site-values.yaml
hanu-reference/service-mesh/site-values.yaml

Change istio operator to istio helm charts
Upgrade charts
- istio-1.13.1
- jaeger-operator-2.27.1 (app: v1.29.1)
- kiali-operator-1.45.1 (app: v1.45.1)
- istio-grafana-dashboard-1.13.1

Upgrade service-mesh version

---

hanu-reference-offline/lma/site-values.yaml
hanu-reference/lma/site-values.yaml

kube-prometheus-stack 차트는 POD로 실행되는 etcd의 exporter 아이피를 서비스 셀렉터를 통해 자동 구성하는 방법을 지원합니다. 이를 위해 kubeEtcd.endpoints 리스트가 비어 있어야 하기 때문에 해당 내용으로 정리하였습니다.

lma: prometheus: fix kubeetcd endpoints

---

hanu-reference/lma/site-values.yaml
hanu-reference/service-mesh/site-values.yaml

- change jaeger, kiali web root
- adopt grafana oidc
* lma 의 grafana.ini 은 값이 override 되지 않는다. 변환할 때 yaml 의 key 값에 "." 이 추가 되면 변환 못시키는 것 같음.
* grafana chart 의 value.yaml 을 보면 grafana.ini:  key 값이 있는데 helm chart 에서는 이 key 를 인식하나 decapod 에서는 인식 못함
* 그렇다 하더라도 추후 변환될 것을 고려하여 override 값을 추가하였음
- 아래 rendering 된 이후에 값들이 변경되므로 workflow 에서 keycloak 에 realms, client 가 생성되면 결과 값을 가져다가 다시 rendering 해야 함. 즉, site.yaml 에서 결정할 수 없는 값이므로 예제 값을 넣었음.
realms: 04a70f29
serviceDomain: taco-cat.xyz
keycloakDomain: keycloak-eom.taco-cat.xyz
grafanaClientSecret: JLtsanYtrCg21RGxrcVmQP0GeuDFUhpA

Adopting servicemesh dashboard

---

.github/workflows/merge_main.yml

렌더링 결과를 decapod-manifests 에 저장할 때 동일한 브랜치 이름을 사용하도록 수정하였습니다.

github-action: use the same branch name for decapod-manifests

---

.github/workflows/merge_main.yml

decapod-site를 포크할 경우 github action에서 push하는 decapod-manifests가 openinfradev로 고정되어 있어,
이를 포크한 사용자의 계정을 사용하도록 변경
변경 전 포크하여 테스트 시 Push되는 decapod-manifest repo
`https://github.com/openinfradev/decapod-manifests`
변경 후 포크한 사용자 계정으로 Push
`https://github.com/Jaesang/decapod-manifests`

Fix destination-github-username to repository owner

---

aws-msa-reference/lma/site-values.yaml
aws-reference/lma/site-values.yaml

aws-mas-reference에도 lma의 경우 loki만 사용하도록 수정합니다.
따라서 현재 들어있는 모든 reference의 lma에서 elastic을 사용하는 부분은 없습니다.
free trial이후 efk를 지원하기 위해서는 reference를 제작해서 수행하거나 이를 지원하기 위한 구조를 새로 설계해야합니다.

efk: remove efk on aws-msa-reference

---

aws-msa-reference/lma/site-values.yaml
aws-reference/lma/site-values.yaml

일자별 테스트가 에러나는 상황 
- 기존 하위호환을 위해 사용하던 kube-dns 서비스
- aws환경의 경우 kube-dns로 존재
- 21의 특정버전이후 이 지원이 삭제됨 https://kubernetes.io/docs/tasks/administer-cluster/coredns/#upgrading-an-existing-cluster-with-kubeadm 
- 추후에는 삭제하더라도 현재 상태 지원을 위해 site값으로 지정

change the dns name for loki to kube-dns

---

aws-msa-reference/lma/site-values.yaml

primary cluster의 적용을 위해 기반 형상을 정의 한다.
- 기본 형상을 single로 정의
- prometheus <- grafana의 형태로 매트릭 조회 
- 클러스터내 loki <- grafana의 형태로 로그 조회
- 위 설정관련 내역중 loki나 prometheus를 변수로 처리하여 primary 설정에서 해당 변수를 변경하여 처리할 수 있도록 함
- thanos형상도 하나로 통일 (primary 변수 제거) 
- 모든 클러스터는 연합형상을 갖고 있지만 primary로 지정한 클러스터에만 thanos 배포

change default for single cluster

---

aws-msa-reference/lma/site-values.yaml

- 현재: grafana → thanos 구조를
- grafana → prometheus 구조로 바꿔줘야함
- 다음 변수를 사용하여 global에서 지정하여 사용
- grafanaDatasourceMetric
- 추가로 loki와 minio를 LoadBalancer 타입으로 열어줘야 다른 조직(org)내 클러스터들이 접근할 수 있음…

primary cluster 체계를 위한 기본값 변경

---

aws-reference/tks-cluster/site-values.yaml
eks-reference/tks-cluster/site-values.yaml

EBS CSI를 위한 권한을 별도 생성한 내역을 사용하는 대신 AWS 에서 관리하는 정책 (arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy) 을 사용하도록 변경합니다.

use AWS managed policy for EBS CSI

---

aws-msa-reference/tks-cluster/site-values.yaml

bucket 이름을 고정으로 변경
현재 primary 구조에서는 organization별 bucket을 생성하고 (현재상황) organization은 계정과 같은 개념이므로 고정명으로 사용가능
추후 organization을 논리적 개념으로 가져가면서 하나의 계정에 여러개 생성가능하도록 하면 이에 대한 수정이 필요한데 현재 organization을 전달하므로 그냥 사용하면 될듯

Ack s3 bucket

---

aws-msa-reference/lma/site-values.yaml

현재 클러스터 생성시 도메인으로 cluster.local을 사용하고 있어 에러가 발생..
thanos의 경우 설정된 clusterDomain을 기반으로 dns 를 통한 통신을 하므로 이를 설정하면 안됨.... -> 일단 주석처리

thanos: disable dns-set

---

eks-msa-reference/lma/kustomization.yaml
eks-msa-reference/lma/site-values.yaml
eks-msa-reference/service-mesh/kustomization.yaml
eks-msa-reference/service-mesh/site-values.yaml
eks-msa-reference/tks-cluster/kustomization.yaml
eks-msa-reference/tks-cluster/site-values.yaml
eks-reference/lma/site-values.yaml
eks-reference/tks-cluster/site-values.yaml

- eks 버전을 v1.25 로 업데이트 
- eks-reference 의 lma 사이트 변수를 aws-msa-reference 값과 동기화
-  eks-msa-reference 사이트 추가 (aws-msa-reference의 lma, service-mesh 기준)

eks: k8s v1.25 지원, eks-msa-reference 사이트 추가

---

aws-msa-reference/lma/site-values.yaml
eks-msa-reference/lma/site-values.yaml

eks에서 etcd를 삭제하기 위해서는 추후 사용하는 부분까지 삭제해야함

do not monitor etcd on eks

---

aws-msa-reference/lma/site-values.yaml
eks-msa-reference/lma/site-values.yaml

rendering을 먼저하는 decapod특성상 구동 버전을 알수 없어서 수동으로 kubernetes 버전을 지정해야 함.

kube-state-metrics: add kube version not to use psp

---

eks-msa-reference/tks-cluster/site-values.yaml
eks-reference/tks-cluster/site-values.yaml

EKS 에서 노드 오토스케일링을 위한 cluster-autoscaler 차트를 추가합니다.
- https://github.com/openinfradev/decapod-base-yaml/pull/227

eks-*-reference: add cluster-autoscaler

---

aws-msa-reference/tks-cluster/site-values.yaml
aws-reference/tks-cluster/site-values.yaml
eks-msa-reference/tks-cluster/site-values.yaml
eks-reference/tks-cluster/site-values.yaml

taco 노드의 min, max 리플리카 수를 3으로 고정합니다. cluster-autoscaler 사용 시 이전 min 값인 1로 변화하는 경우가 있고 3 노드에서 변동은 없을 것으로 생각합니다.

tks-cluser: make taco node's min. and max. replicas to 3

---

aws-msa-reference/lma/site-values.yaml
aws-reference/lma/site-values.yaml
eks-msa-reference/lma/site-values.yaml
eks-reference/lma/site-values.yaml

loki에서 생성하는 disk가 default가 아닌 명시적으로 지정한 것을 사용하도록 변경합니다.

loki: explicitly define storage class name

---

aws-msa-reference/lma/site-values.yaml
aws-reference/lma/site-values.yaml
eks-msa-reference/lma/site-values.yaml
eks-reference/lma/site-values.yaml

minio에 올라가는 객체에 대한 ilm을 추가함에 따라 과도한 디스크를 할당했었던 부분을 수정합니다.
- from: 3TB
- to: 500GB

minio: reduce default storage size

---

aws-msa-reference/lma/site-values.yaml
aws-reference/lma/site-values.yaml
eks-msa-reference/lma/site-values.yaml
eks-reference/lma/site-values.yaml

버킷이 비워지지 않아서 클러스터가 삭제되지 않는 버그에 대한 수정입니다.
다음 내역이 한꺼번에 merge되어야 합니다.
- https://github.com/openinfradev/helm-charts/pull/194
- https://github.com/openinfradev/decapod-base-yaml/pull/252
- https://github.com/openinfradev/decapod-site/pull/166

ack-resources: add controllerability for versioned objects on s3 buckets

---

aws-msa-reference/tks-cluster/site-values.yaml
aws-reference/tks-cluster/site-values.yaml
eks-msa-reference/tks-cluster/site-values.yaml
eks-reference/tks-cluster/site-values.yaml

- Minimal deploy support
함께 merge되어야 할 것들
- https://github.com/openinfradev/decapod-site/pull/174
- https://github.com/openinfradev/decapod-base-yaml/pull/262
- https://github.com/openinfradev/tks-flow/pull/251

최소사항 클러스터 지원을 위한 여정 

---

aws-reference/tks-admin-tools/site-values.yaml
byoh-reference/tks-admin-tools/site-values.yaml
eks-reference/tks-admin-tools/site-values.yaml

ingress-ngnix 를 tks-admin-tools 그룹에 복사합니다.
nodeSelector 및 namespace 등 설정이 usercluster 배포 시와는 다르므로 별도의 entry가 필요합니다.
다음 PR도 함께 머지되어야 합니다.
https://github.com/openinfradev/decapod-base-yaml/pull/266

Clone ingress nginx

---

byoh-reference/tks-cluster/site-values.yaml

각 클러스터를 위한 byoh 레이블 형식을 다음과 같이 사용하도록 수정하였습니다.
- CLUSTER_ID-control-plane
- CLUSTER_ID-tks
- CLUSTER_ID-worker

byoh: use dedicated byoh label selectors for each cluster

---

aws-msa-reference/tks-cluster/site-values.yaml
aws-reference/tks-cluster/site-values.yaml
eks-msa-reference/tks-cluster/site-values.yaml
eks-reference/tks-cluster/site-values.yaml

**https://github.com/openinfradev/decapod-base-yaml/pull/276 과 같이 반영이 되어야 합니다.**
Mananged Control plane과 EKS 각각 분리해서 사용하던 cluster-autoscaler 차트를 업스트림 차트([https://github.com/kubernetes/autoscaler/tree/master/charts/cluster-autoscaler)로](https://github.com/kubernetes/autoscaler/tree/master/charts/cluster-autoscaler)%EB%A1%9C) 통일합니다.
이력
Managed controle plane: cluster-api 프로바이더 지원을 위한 내역이 부족하여 업스트림과 별도로 차트를 만들어서 사용 (https://github.com/openinfradev/helm-charts/tree/main/cluster-autoscaler)
EKS: AWS 프로바이더를 사용하여 적용
최신 버전에서는 cluster-api 프로바이더를 위해 필요한 부분도 모두 포함되어 있어 업스트림 차트를 공통적으로 사용하도록 수정
차이점
- aws*-reference: K8S 버전 1.26.10, cluster-autoscaler 버전 1.26.4
- eks*-reference: K8S 버전 1.25.9, cluster-autoscaler 버전 1.25.3

make the upstream cluster-autoscaler chart common to all

---

aws-msa-reference/tks-cluster/site-values.yaml
aws-reference/tks-cluster/site-values.yaml

cluster-autoscaler 에서 참조하는 어드민 클러스터의 kubeconfig 파일 경로가 잘못되어 있어 수정합니다.

fix cloud kubeconfig path for cluster-autoscaler

---

aws-msa-reference/lma/site-values.yaml
aws-reference/lma/site-values.yaml
eks-msa-reference/lma/site-values.yaml
eks-reference/lma/site-values.yaml

thanos-storegateway 에서 S3 접근 권한 이슈를 수정합니다.
EKS 환경에서는 발생한 적이 없으나 업스트림 이슈를 보면 EKS에서도 발생할 가능성이 있어 모든 사이트에 대해 값을 수정하였습니다. Thanos 관련 문서를 봐도 AWS 인증 방식을 사용하기 위해서는 true로 설정하는 것이 맞아 보입니다.
참고:
- https://github.com/thanos-io/thanos/issues/5929#issuecomment-1600459874
- https://github.com/thanos-io/thanos/blob/main/docs/storage.md
> However if you set aws_sdk_auth: true Thanos will use the default authentication methods of the AWS SDK for go based on [known environment variables](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html) (AWS_PROFILE, AWS_WEB_IDENTITY_TOKEN_FILE ... etc) and known AWS config files (~/.aws/config). If you turn this on, then the bucket and endpoint are the required config keys.

lma: fix thanos storegateway permissions for S3

---

aws-msa-reference/tks-cluster/site-values.yaml
aws-reference/tks-cluster/site-values.yaml

aws*-reference 환경에서 사용하는 기본 OS를 Ubuntu 22.04로 변경합니다. 현재까지는 별도 설정 없이 기본 값인 Ubuntu 18.04가 사용되었었습니다.

aws*-reference: use ubuntu-22.04 for base OS

---

aws-msa-reference/tks-cluster/site-values.yaml
aws-reference/tks-cluster/site-values.yaml

프로덕션 환경 적용을 위한 aws*-reference 사이트 수정입니다.
- 컨트롤 플레인 형상은 고정: 3 nodes x t3.large
- OS: Ubuntu 20.04 (22.04는 CAPA에서 AMI 이미지 미제공)
- 사용자 워커 노드는 MachineDeployment로 변경
- 총 노드 수는 콘솔에서 입력 받은 개수 * AZ 개수로 구성: 각 AZ마다 MachineDeployment 배포
- AZ개수는 ap-northeast-2 기준 3개로 소정
- 현재는 cluster-autoscaler를 위한 min(tksUserNode), max(tksUserNodeMax) 개수가 기본 배포하는 개수(tksUserNode)와 동일하기 때문에 자동 확장 되지는 않습니다.

fix aws*-reference for production

---

aws-msa-reference/tks-cluster/site-values.yaml
aws-reference/tks-cluster/site-values.yaml

aws*-reference 컨트롤 플레인 노드 타입을 m6i.2xlarge으로 사용합니다. (CA팀 요청 사항)

aws*-reference: use m6i.2xlarge for control plane node

---

aws-msa-reference/tks-cluster/site-values.yaml
aws-reference/tks-cluster/site-values.yaml
eks-msa-reference/tks-cluster/site-values.yaml
eks-reference/tks-cluster/site-values.yaml

사용자가 입력한 값을 cluster min 값으로 사용한다.
eks
. min, max 모두 동일 값 사용.
aws
. min, max 모두 동일 값 사용. ( 단 이는 az 당 min, max 값으로 실제 개수는 * az개수 가 됨 )

bugfix. set node min value as users data

---

aws-msa-reference/tks-cluster/site-values.yaml
aws-reference/tks-cluster/site-values.yaml
byoh-reference/tks-cluster/site-values.yaml
eks-msa-reference/tks-cluster/site-values.yaml
eks-reference/tks-cluster/site-values.yaml

k8s version 을 v.1.29.8 로 업데이트 합니다.
byoh-hostagent 는 rocky image 를 업데이트 함.
```
curl -v --user ID:PASSWORD --upload-file byoh-hostagent-linux-amd64 http://localhost:3001/api/packages/decapod10/generic/byoh_hostagent/v0.5.0-tks-20240403/byoh-hostagent-linux-amd64
```

Update tks k8s version
